name: Deploy Node Applications

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          export DOCKER_BUILDKIT=1
          docker build -t mamatha12345678/kcc-node -f backend/Dockerfile backend

      - name: Publish Image to Docker Hub
        run: docker push mamatha12345678/kcc-node:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: docker pull mamatha12345678/kcc-node:latest

      - name: Remove Old Container (if exists)
        run: docker rm -f nodejs-app-container || true

      - name: Run Docker Container
        run: |
          docker run -d -p 8000:8000 --name nodejs-app-container \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e JWT_EXPIRE="${{ secrets.JWT_EXPIRE }}" \
            -e PORT="${{ secrets.PORT }}" \
            -e FRONTEND_URL="${{ secrets.FRONTEND_URL }}" \
            mamatha12345678/kcc-node:latest
